language: node_js
addons:
  chrome: stable
env:
  - CHROME_BIN: google-chrome-stable
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - yarn lint && yarn test
before_deploy:
  - NODE_ENV=production yarn build
deploy:
  provider: heroku
  api_key:
    secure: NKPD1XpyAIefkCqT5EevKSSsNLuwP5ZcAc+fO1TT6eJcYh3J3ZEaEF8lPMibD65D+qChuyNqP9c1zMl6kC9Ia3D8QmLrAZopZOWEEgTe09GDJYxvx0RYEsd/t6OWuhCvuT/gvFJ8x2oWLkaB0/r0Ogi3gdq4FuIHNDaW5KXD+j4=
  skip_cleanup: true
