version: 2.1

executors:
  default:
    working_directory: ~/monopoly-wallet
    docker:
      - image: circleci/node:11-browsers

jobs:
  install:
    executor: default
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - monopoly-wallet-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - monopoly-wallet-{{ .Branch }}-
            - monopoly-wallet-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          name: Save cache
          key: monopoly-wallet-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - app/node_modules
            - server/node_modules
      - persist_to_workspace:
          root: ~/
          paths:
            - monopoly-wallet
            - .ssh

  lint:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Lint
          command: yarn lint

  build-app:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build app
          command: yarn app build
      - persist_to_workspace:
          root: ~/
          paths:
            - monopoly-wallet/app/dist

  build-server:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build server
          command: yarn server build
      - persist_to_workspace:
          root: ~/
          paths:
            - monopoly-wallet/server/dist

  test-app:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run app tests
          command: yarn app test:ci:percy
          environment:
            JUNIT_FILE: ./junit/test-results.xml
      - store_test_results:
          path: ./app/junit

  test-server:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run server tests
          command: yarn server test:ci
          environment:
            JUNIT_FILE: ./junit/test-results.xml
      - store_test_results:
          path: ./server/junit

workflows:
  version: 2
  default:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build-app:
          requires:
            - lint
      - build-server:
          requires:
            - lint
      - test-app:
          requires:
            - lint
      - test-server:
          requires:
            - lint
