references:
  defaults: &defaults
    working_directory: ~/monopoly-wallet
    docker:
      - image: circleci/node:11-browsers

  cache_key: &cache_key
    monopoly-wallet-{{ .Branch }}-{{ checksum "yarn.lock" }}-v1

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          key: *cache_key
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          name: Save cache
          key: *cache_key
          paths:
            - node_modules
            - app/node_modules
            - server/node_modules
      - persist_to_workspace:
          root: ~/
          paths:
            - monopoly-wallet
            - .ssh

  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Lint
          command: yarn lint

  build-app:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Build app
          command: yarn app build
      - persist_to_workspace:
          root: ~/
          paths:
            - monopoly-wallet/app/dist

  build-server:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Build server
          command: yarn server build
      - persist_to_workspace:
          root: ~/
          paths:
            - monopoly-wallet/server/dist

  test-app:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Run app tests
          command: yarn app test --single-run

  test-server:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Run server tests
          command: yarn server test

workflows:
  version: 2
  default:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build-app:
          requires:
            - install
      - build-server:
          requires:
            - install
      - test-app:
          requires:
            - build-app
      - test-server:
          requires:
            - build-server
